project:
  type: website  
  output-dir: docs

bibliography: references.bib
link-citations: true

author: "Jianshu Wu"

website:
  title: "CASA0023 Learning Diary"
  repo-url: "https://github.com/brotree-code/casa0023-diary" 
  repo-actions: [source, issue]
  search: true

  
  navbar:
    background: light  
    pinned: false  
    
    right:
      - icon: github
        href: "https://github.com/brotree-code/casa0023-diary"
        aria-label: GitHub

  
  sidebar:
    style: docked
    contents:
      - text: "Welcome"
        file: index.qmd
      - text: "Week 1: Intro & Spectral" 
        file: week1.qmd
      - text: "Week 2: Sensor Presentation"
        file: week2.qmd
      - text: "Week 3: Corrections & Enhancements"
        file: week3.qmd
      - text: "Week 4＆5: EO & Policy"
        file: week4_5.qmd
      - text: "Week 6: Google Earth Engine I"
        file: week6.qmd
      - text: "Week 7: Classification I"
        file: week7.qmd
      - text: "Week 8: Classification II"
        file: week8.qmd   
format:
  html:
    
    css: styles.css
    include-after-body: corner-image.html

    theme:
      light: flatly
      dark: darkly
      
    header-includes: |
      <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;700&display=swap" rel="stylesheet">
    mainfont: "Nunito"
    fontsize: 1.1em       
    fontcolor: "#333333"  

    toc: true
    toc-depth: 3
    toc-location: right
    code-fold: true
    code-summary: "Show code"
    number-sections: false